### ISSUE TITLE
RWD 響應式網頁設計-內容設計

### ISSUE THREAD

**Issue by gagajhuang** [gagajhuang/hexschool-course-notes#3]
## 表格設計
- 不必要資訊可隱藏
- width 須設定%數
- 解決縮小後，字變直排的問題
 - 表格出現橫向卷軸：`overflow-x:auto`
 - width 固定 px
 - 使用 data- 更改為直式單列表格
```html
<table class="rwd-table">
   <thead>
     <tr>
       <th>基金名稱</th>
       <th>一年<br>報酬率</th>
       <th>二年<br>報酬率</th>
       <th>三年<br>報酬率</th>
     </tr>
   </thead>
   <tbody>
     <tr>
       <td class="rateblock"  data-th="基金名稱">本基金</td>
       <td data-th="一年報酬率">22.61</td>
       <td data-th="二年報酬率">3.15</td>
       <td data-th="三年報酬率">42.53</td>
     </tr>
   </tbody>
</table>
```
```css
.rwd-table th{
  display: none;
}
.rwd-table td{
  display: block;
  line-height: 25px;
}
.rwd-table td:nth-child(odd){
  background: #f7d4d4
}
.rwd-table td.currency{
  background: #7f0b0a;
  color: #fff
}
.rwd-table td.rateblock{
  background: #c3c3c3;
}
.rwd-table td:before {
  width: 100%;
  content: attr(data-th);
  float: left;
  font-weight: bold;
}
```
![GITHUB]( 圖片網址 "圖片名稱")
